### ISSUE TITLE
Creating a budget for non organ that is currently not active anymore gives exception

### ISSUE THREAD

**Issue by stefanmajoor** [GEWIS/gewisdb#86]
When creating a budget for a currently non active organ gives a "Doctrine\Common\Proxy\Exception\InvalidArgumentException", even if at the moment of the meeting the organ exists.

What should happen:

- Display an error message if the meeting takes place at a moment the organ does not exist
- No error should be displayed if the meeting takes place the moment an organ does exist

**Comment by kokx** [comment]
What do you mean with an organ that is not active anymore?

Note btw that, to keep things sane, the database does not consider the state at the moment of the meeting. It rather considers the state at the moment of the last meeting in the database.

**Comment by stefanmajoor** [comment]
> What do you mean with an organ that is not active anymore?

If somewhere in a meeting an organ is abrogated somewhere in the database

> Note btw that, to keep things sane, the database does not consider the state at the moment of the meeting. It rather considers the state at the moment of the last meeting in the database.

I think that it might be possible to make it such that it does detect which organs are active. However, either way this exception message must be changed for a good error message

**Comment by kokx** [comment]
Ah, OK, now I see what is happening here. After taking a look at the implementation of organs in the budget part, it seems that we will need some refactoring here. Because it would be better to do the 

When I'm looking at it, I don't think that we even need to have an organ in such a decision. Because it is not in the formulation of the decision anyway.
